---
name: "Chad West"
id: "ChadWest"
path_to_contributions_data: "../candidates/West/Data/west_contributions.json"
path_to_headshot_photo: "../candidates/West/West_headshot.jpeg"
path_to_maps:
  - "../candidates/West/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/West/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/West/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/West/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2019"
next_election: "2025"
district: "1"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Jesus Moreno"
id: "JesusMoreno"
path_to_contributions_data: "../candidates/Moreno/Data/moreno_contributions.json"
path_to_headshot_photo: "../candidates/Moreno/Visuals/Moreno_headshot.png"
path_to_maps:
  - "../candidates/Moreno/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Moreno/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Moreno/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "2"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Zarin Gracey"
id: "ZarinGracey"
path_to_contributions_data: "../candidates/Gracey/Data/gracey_contributions.json"
path_to_headshot_photo: "../candidates/Gracey/Visuals/Gracey_headshot.jpeg"
path_to_maps:
  - "../candidates/Gracey/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Gracey/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2023"
next_election: "2025"
district: "3"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Carolyn Arnold"
id: "CarolynArnold"
path_to_contributions_data: "../candidates/Arnold/Data/arnold_contributions.json"
path_to_headshot_photo: "../candidates/Arnold/Visuals/Arnold_headshot.jpeg"
path_to_maps:
  - "../candidates/Arnold/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2019"
next_election: "2025"
district: "4"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Jaime Resendez"
id: "JaimeResendez"
path_to_contributions_data: "../candidates/Resendez/Data/resendez_contributions.json"
path_to_headshot_photo: "../candidates/Resendez/Visuals/Resendez_headshot.jpeg"
path_to_maps:
  - "../candidates/Resendez/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "5"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Omar Narvaez"
id: "OmarNarvaez"
path_to_contributions_data: "../candidates/Narvaez/Data/narvaez_contributions.json"
path_to_headshot_photo: "../candidates/Narvaez/Visuals/Narvaez_headshot.jpeg"
path_to_maps:
  - "../candidates/Narvaez/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2017"
next_election: "2025"
district: "6"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Adam Bazaldua"
id: "AdamBazaldua"
path_to_contributions_data: "../candidates/Bazaldua/Data/bazaldua_contributions.json"
path_to_headshot_photo: "../candidates/Bazaldua/Visuals/Bazaldua_headshot.jpeg"
path_to_maps:
  - "../candidates/Bazaldua/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2019"
next_election: "2025"
district: "7"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Tennell Atkins"
id: "TennellAtkins"
path_to_contributions_data: "../candidates/Atkins/Data/Atkins_contributions.json"
path_to_headshot_photo: "../candidates/Atkins/Visuals/Atkins_headshot.png"
path_to_maps:
  - "../candidates/Atkins/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Atkins/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Ridley/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Atkins/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2017"
next_election: "2025"
district: "8"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Paula Blackmon"
id: "PaulaBlackmon"
path_to_contributions_data: "../candidates/Blackmon/Data/blackmon_contributions.json"
path_to_headshot_photo: "../candidates/Blackmon/Visuals/Blackmon_headshot.png"
path_to_maps:
  - "../candidates/Blackmon/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "9"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Kathy Stewart"
id: "KathyStewart"
path_to_contributions_data: "../candidates/Stewart/Data/stewart_contributions.json"
path_to_headshot_photo: "../candidates/Stewart/Visuals/Stewart_headshot.jpeg"
path_to_maps:
  - "../candidates/Stewart/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Stewart/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2023"
next_election: "2025"
district: "10"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Jaynie Schultz"
id: "JaynieSchultz"
path_to_contributions_data: "../candidates/Schultz/Data/schultz_contributions.json"
path_to_headshot_photo: "../candidates/Schultz/Visuals/Schultz_headshot.jpeg"
path_to_maps:
  - "../candidates/Schultz/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Schultz/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Schultz/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "11"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Cara Mendelsohn"
id: "CaraMendelsohn"
path_to_contributions_data: "../candidates/Mendelsohn/Data/mendelsohn_contributions.json"
path_to_headshot_photo: "../candidates/Mendelsohn/Visuals/Mendelsohn_headshot.jpeg"
path_to_maps:
  - "../candidates/Mendelsohn/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Mendelsohn/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Mendelsohn/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Mendelsohn/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2017"
next_election: "2025"
district: "12"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Gay Willis"
id: "GayWillis"
path_to_contributions_data: "../candidates/Willis/Data/willis_contributions.json"
path_to_headshot_photo: "../candidates/Willis/Visuals/Willis_headshot.png"
path_to_maps:
  - "../candidates/Willis/Visuals/May 5, 2019 - May 4, 2021.jpeg"
  - "../candidates/Willis/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Willis/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "13"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Paul Ridley"
id: "PaulRidley"
path_to_contributions_data: "../candidates/Ridley/Data/ridley_contributions.json"
path_to_headshot_photo: "../candidates/Ridley/Visuals/Ridley_headshot.jpeg"
path_to_maps:
  - "../candidates/Ridley/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Ridley/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Ridley/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "14"
city: "Dallas"
election_status: "in-office"
election_day: "05-04"
individual_limit: 1000
pac_limit: 2500
---
name: "Sukh Kaur"
id: "SukhKaur"
path_to_contributions_data: "../candidates/SukhKaur/sukhkaur_contributions.json"
path_to_headshot_photo: "../candidates/SukhKaur/kaur_headshot.jpeg"
path_to_maps:
  - "../candidates/West/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/West/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/West/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/West/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2023"
next_election: "2025"
district: "1"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Jalen McKee-Rodriguez"
id: "JalenMcKee-Rodriguez"
path_to_contributions_data: "../candidates/JalenMcKee-Rodriguez/JalenMcKeeRodriguez_contributions.json"
path_to_headshot_photo: "../candidates/JalenMcKee-Rodriguez/rodriguez_headshot.png"
path_to_maps:
  - "../candidates/Moreno/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Moreno/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Moreno/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "2"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Phyllis Viagran"
id: "PhyllisViagran"
path_to_contributions_data: "../candidates/PhyllisViagran/PhyllisViagran_contributions.json"
path_to_headshot_photo: "../candidates/PhyllisViagran/viagran_headshot.jpeg"
path_to_maps:
  - "../candidates/Gracey/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Gracey/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "3"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Adriana Garcia"
id: "AdrianaGarcia"
path_to_contributions_data: "../candidates/AdrianaGarcia/AdrianaGarcia_contributions.json"
path_to_headshot_photo: "../candidates/AdrianaGarcia/garcia_headshot.jpeg"
path_to_maps:
  - "../candidates/Arnold/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Arnold/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2019"
next_election: "2025"
district: "4"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Teri Castillo"
id: "TeriCastillo"
path_to_contributions_data: "../candidates/TeriCastillo/TeriCastillo_contributions.json"
path_to_headshot_photo: "../candidates/TeriCastillo/castillo_headshot.jpeg"
path_to_maps:
  - "../candidates/Resendez/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Resendez/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2021"
next_election: "2025"
district: "5"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Melissa Cabello Havrda"
id: "MelissaCabelloHavrda"
path_to_contributions_data: "../candidates/MelissaCabelloHavrda/MelissaCabelloHavrda_contributions.json"
path_to_headshot_photo: "../candidates/MelissaCabelloHavrda/havrda_headshot.jpeg"
path_to_maps:
  - "../candidates/Narvaez/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Narvaez/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2019"
next_election: "2025"
district: "6"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Marina Gavito"
id: "MarinaGavito"
path_to_contributions_data: "../candidates/MarinaGavito/MarinaGavito_contributions.json"
path_to_headshot_photo: "../candidates/MarinaGavito/gavito_headshot.jpeg"
path_to_maps:
  - "../candidates/Bazaldua/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Bazaldua/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2023"
next_election: "2025"
district: "7"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Manny Pelaez"
id: "MannyPelaez"
path_to_contributions_data: "../candidates/MannyPelaez/MannyPelaez_contributions.json"
path_to_headshot_photo: "../candidates/MannyPelaez/pelaez_headshot.jpeg"
path_to_maps:
  - "../candidates/Atkins/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Atkins/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Ridley/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Atkins/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2017"
next_election: "2025"
district: "8"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "John Courage"
id: "JohnCourage"
path_to_contributions_data: "../candidates/JohnCourage/JohnCourage_contributions.json"
path_to_headshot_photo: "../candidates/JohnCourage/courage_headshot.jpeg"
path_to_maps:
  - "../candidates/Blackmon/Visuals/May 5, 2017 - May 4, 2019.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2019 - May 4, 2021.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Blackmon/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2017"
next_election: "2025"
district: "9"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500
---
name: "Marc Whyte"
id: "MarcWhyte"
path_to_contributions_data: "../candidates/MarcWhyte/MarcWhyte_contributions.json"
path_to_headshot_photo: "../candidates/MarcWhyte/whyte_headshot.jpeg"
path_to_maps:
  - "../candidates/Stewart/Visuals/May 5, 2021 - May 4, 2023.jpg"
  - "../candidates/Stewart/Visuals/May 5, 2023 - May 4, 2025.jpg"
first_election: "2023"
next_election: "2025"
district: "10"
city: "San Antonio"
election_status: "in-office"
election_day: "06-01"
individual_limit: 500
pac_limit: 500