---
name: "Chad West"
id: "ChadWest"
path_to_contributions_data: "../candidates/West/Data/west_contributions.json"
path_to_headshot_photo: "../candidates/West/West_headshot.jpeg"
path_to_maps:
  - "../candidates/West/Visuals/2017_thru_2019.jpg"
  - "../candidates/West/Visuals/2019_thru_2021.jpg"
  - "../candidates/West/Visuals/2021_thru_2023.jpg"
  - "../candidates/West/Visuals/2023_thru_2025.jpg"
first_election: "2019"
next_election: "2025"
district: "1"
city: "Dallas"
election_status: "in-office"
---
name: "Jesus Moreno"
id: "JesusMoreno"
path_to_contributions_data: "../candidates/Moreno/Data/moreno_contributions.json"
path_to_headshot_photo: "../candidates/Moreno/Visuals/Moreno_headshot.png"
path_to_maps:
  - "../candidates/Moreno/Visuals/JesusMoreno_donors_map_2019-2021_highlighted.jpg"
  - "../candidates/Moreno/Visuals/JesusMoreno_donors_map_2021-2023_highlighted.jpg"
  - "../candidates/Moreno/Visuals/JesusMoreno_donors_map_2023-2025_highlighted.jpg"
first_election: "2021"
next_election: "2025"
district: "2"
city: "Dallas"
election_status: "in-office"
---
name: "Zarin Gracey"
id: "ZarinGracey"
path_to_contributions_data: "../candidates/Gracey/Data/gracey_contributions.json"
path_to_headshot_photo: "../candidates/Gracey/Visuals/Gracey_headshot.jpeg"
path_to_maps:
  - "../candidates/Gracey/Visuals/ZarinGracey_donors_map_2021-2023_highlighted.jpg"
  - "../candidates/Gracey/Visuals/ZarinGracey_donors_map_2023-2025_highlighted.jpg"
first_election: "2023"
next_election: "2025"
district: "3"
city: "Dallas"
election_status: "in-office"